spring:
  datasource:
    url: jdbc:postgresql://pgpro.corp.inversion.ru:5432/pgdev?escapeSyntaxCallMode=callIfNoReturn 
    username: sulimoff
    password: qqq
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 12
  output:
    ansi:
      enabled: always

  rabbitmq:
    addresses: amqp://rabbit.corp.inversion.ru:5672/cbsbus_pg
    username: cbsbus
    password: ${decrypt:7hDm5VDrSaGnHSuBJF3TzA==}
    listener:
      simple:
        concurrency: 2
        max-concurrency: 2

mi:
  consul:
      host: 192.168.0.35
      port: 8500

service:
  name: xxl-gate

logging:
  file:
    name: "log/${service.name}.log"

  charset:
    console: UTF-8
    file: UTF-8

  level:
    root: INFO

    ru.inversion: INFO

    org.springframework: WARN
    org.springframework.amqp: WARN
    com.rabbitmq.client: WARN
    com.rabbitmq: WARN
    com.zaxxer.hikari: WARN
    com.zaxxer.hikari.HikariConfig: INFO

  logback:
    rollingpolicy:
      max-history: 14

  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level%X{xxl.console.prefix} [%thread] %logger{40} : %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level%X{xxl.file.prefix} [%thread] %logger{40} : %msg%n"