spring:
  application:
    name: xxl-gate

  rabbitmq:
    listener:
      type: simple
      simple:
        acknowledge-mode: auto
        concurrency: 2
        max-concurrency: 2
        retry:
          enabled: false
        # Если есть медленные операции, вроде http-запросов или медленной работы с БД, поставьте 1. В противном случае больше.
        prefetch: 1

service:
  name: xxl-gate
